### ISSUE TITLE
Incorrect results in Random Event Focus Table

### ISSUE THREAD

**Issue by vandora03** [saif-ellafi/foundryvtt-mythic-gme#31]
The "PC Positive" result (roll range of 81-85 for 1d100) under Random Event Focus Table is missing under the "Mythic GME: Event Focus (2e)" table. Also, it seems when 2nd Edition rulebook is selected, the "Random Event" button still leads to 1st edition Event Focus table instead of the 2nd edition version table.

**Comment by saif-ellafi** [comment]
Wow, thank you for checking @vandora03 - I accepted this pull request to the table without reviewing it.
Will fix asap in next release. For the button, will check again

**Comment by saif-ellafi** [comment]
Should be fixed in 2.8.3 thank you!

**Comment by Matt-410** [comment]
This is still an issue, I'm using the most recent version according to Foundry. When I roll a Random Event, the focus came up as 39, which in 2e should be NPC Action, I'm getting Move toward a Thread. In addition the action and second word are not correct for the roll. I don't know what the second word is called in 2e, it was subject in the 1st edition. Now it's either a description or element. Not sure what it's pulling from.
