### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by coppolaop** [saif-ellafi/foundryvtt-mythic-gme#68]
Hi!
I was using the module this weekend and I got some words in english, maybe it's a i18n call missing.
I tryed to take a look over the code but I didn't find where the problem is.
It happens in this parts:

### Event Focus
<img width="297" height="170" alt="Image" src="https://github.com/user-attachments/assets/0195f494-5490-43b5-9c71-85aa4578d989" />

### Random events
<img width="295" height="253" alt="Image" src="https://github.com/user-attachments/assets/76b9da66-4288-4959-b7d0-485a4491eebc" />

### Unexpected random events (because its also a random event)
<img width="294" height="580" alt="Image" src="https://github.com/user-attachments/assets/d2544388-d1ef-4e38-b99b-b4dcb5e5e5f8" />

If I find something, I'll post it here as comment.

**Comment by Andyvec** [comment]
Hi,

I see that this issue is still around.
Some rolls returns English descriptions no matte which language has been set.

@coppolaop did you hot any clue about it?

**Comment by coppolaop** [comment]
@Andyvec, are there any missing i18n tags?

**Comment by saif-ellafi** [comment]
Should have been fixed in the last release. Is it not?

**Comment by Andyvec** [comment]
@saif-ellafi Is not fixed yet.
I'm in the latest version, all set in Spanish, but still got half of the Mythic content in English. And everything else 100% in English.

<img width="872" height="933" alt="Image" src="https://github.com/user-attachments/assets/a4dabc1f-c2da-400e-ae5c-6bf15c2dc9ad" />

<img width="475" height="420" alt="Image" src="https://github.com/user-attachments/assets/47b8686b-ffdf-4b2c-8d8e-f46d09d18787" />

<img width="689" height="406" alt="Image" src="https://github.com/user-attachments/assets/ae1dfbee-c936-4b6c-900f-bd3c92e754cd" />

**Comment by saif-ellafi** [comment]
Alright, what a pity. Then we might need to regenerate the databases. Unfortunately I'm off till around 24th june
